from django.db import models
from django.contrib.auth.models import User


class GeneratedContent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.CharField(max_length=100)
    prompt = models.TextField()
    tone = models.CharField(max_length=100)
    generated_text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    content_type_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.content_type} generated by {self.user} on {self.created_at}"
